config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :staff_members

  get 'pages/home'

  get 'pages/contacts'

  devise_for :users  
  resources :store
  

      
  

 

   
   root 'pages#home'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /^image\/(png|gif|jpg|jpeg)/,
 	message: "only images are allowed"
 	validates :image, attachment_presence: true
	
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/staff_member.rb
class StaffMember < ActiveRecord::Base
	ratyrate_rateable 'smiling', 'kindness', 'friendly', 'professional'
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 	has_attached_file :resource
 	#validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart
  ratyrate_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!

    

end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

 


    #helper_method :set_cart

    def countItems
      countObjects=0
      #user.cart.line_items  se vogliamo sapere gli oggetti di un utente
      set_cart.line_items.each do |item|
        countObjects += item.quantity
      end
      return countObjects   
    end 
    #helper_method :countItems
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!

  def home
  	if current_user
  		redirect_to store_index_path
  	end 
  end

  def contacts
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :decription, :price,:image)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/staff_members_controller.rb
class StaffMembersController < ApplicationController
  before_action :set_staff_member, only: [:show, :edit, :update, :destroy]

  # GET /staff_members
  # GET /staff_members.json
  def index
    @staff_members = StaffMember.all
  end

  # GET /staff_members/1
  # GET /staff_members/1.json
  def show
  end

  # GET /staff_members/new
  def new
    @staff_member = StaffMember.new
  end

  # GET /staff_members/1/edit
  def edit
  end

  # POST /staff_members
  # POST /staff_members.json
  def create
    @staff_member = StaffMember.new(staff_member_params)

    respond_to do |format|
      if @staff_member.save
        format.html { redirect_to @staff_member, notice: 'Staff member was successfully created.' }
        format.json { render :show, status: :created, location: @staff_member }
      else
        format.html { render :new }
        format.json { render json: @staff_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff_members/1
  # PATCH/PUT /staff_members/1.json
  def update
    respond_to do |format|
      if @staff_member.update(staff_member_params)
        format.html { redirect_to @staff_member, notice: 'Staff member was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff_member }
      else
        format.html { render :edit }
        format.json { render json: @staff_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staff_members/1
  # DELETE /staff_members/1.json
  def destroy
    @staff_member.destroy
    respond_to do |format|
      format.html { redirect_to staff_members_url, notice: 'Staff member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff_member
      @staff_member = StaffMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_member_params
      params.require(:staff_member).permit(:fullname, :image, :role, :resource)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
	def index
		@staff_members = StaffMember.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def comment
	end



	def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
	end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end





end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/staff_members_helper.rb
module StaffMembersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<% @cart.ordered_products.each do |item| %>
<!-- START_HIGHLIGHT -->

  <tr >
    <td><%= item.product.title %> </td>
    <td><%= item.product.price %></td>
    <td><%= item.quantity %></td>
    <td><%= item.product.price * item.quantity %> </td>
    <td><%= link_to "Delete",ordered_products_path(item) %> </td>
  </tr>

<% end %>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/_navbar.html.erb
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= store_index_path %>">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= ordered_products_url %>"><i class="fa fa-shopping-cart fa-sm"><div id="total_items"><%= @total_items %></div></i></a></li>
        
        <li class="dropdown">

          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
  <%= current_user.email %>
<% end %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="<%=edit_user_registration_url %>">Settings</a></li>
            <li><a href="#">another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="<%= destroy_user_session_path %>">Sign out</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
  <title>Carr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>

  <!-- <p class="notice"><%= notice %></p> -->
      <!-- <p class="alert"><%= alert %></p> -->

<%= flash_messages %>

<div class="container">

	 	

<%= yield %>
</div>

</body>
</html>

app/views/pages/contacts.html.erb
<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/home.html.erb
<h1>YOU ARE IN HOME</h1>

app/views/products/_form.html.erb
<%= simple_form_for(@product, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>
 
 
    <%= f.input :title, required: true, label: false, placeholder: "Title", input_html: {class: "form-control"} %>
    
    <%= f.input :decription, required: true, label: false, placeholder: "Description", input_html: {class: "form-control", rows: 5} %>
    <br>
    <%= f.input :price, required: true, label: false, placeholder: "Price", input_html: {class: "form-control"} %>
    
    <%= f.input :image %>
        
    <div class="checkbox text-center">
    <p>Availability</p>
   
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Decription</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.decription %></td>
        <td><%= product.price %></td>
        <td><%= product.image %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Decription:</strong>
  <%= @product.decription %>
</p>
<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/staff_members/_form.html.erb
<%= simple_form_for @staff_member, url: staff_members_path,html: {multipart: true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :fullname %>
    <%= f.input :image, as: :file %>
    <%= f.input :role %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/staff_members/edit.html.erb
<h1>Editing Staff Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff_member %> |
<%= link_to 'Back', staff_members_path %>

app/views/staff_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staff Members</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Photo</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staff_members.each do |staff_member| %>
      <tr>
        <td><%= staff_member.fullname %></td>
        <td><%= image_tag staff_member.image.url(:original), class: "img-responsive" %></td>
        <td><%= staff_member.role %></td>
        <td><%= link_to 'Show', staff_member %></td>
        <td><%= link_to 'Edit', edit_staff_member_path(staff_member) %></td>
        <td><%= link_to 'Destroy', staff_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff member', new_staff_member_path %>

app/views/staff_members/new.html.erb
<h1>New Staff Member</h1>

<%= render 'form' %>

<%= link_to 'Back', staff_members_path %>

app/views/staff_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @staff_member.fullname %>
</p>

<p>
  <strong>Photo:</strong>
 
  <%= image_tag @staff_member.image.url(:original), class: "img-responsive" %>
</p>

<p>
  <strong>Role:</strong>
  <%= @staff_member.role %>
</p>



<div class="row">
  <div class="small-2 large-2 columns">
    <%= imdb_style_rating_for @staff_member, current_user%>
  </div>
  <br>
  <div class="small-2 large-4 columns">
    <% if current_user %>
      Smiling: <%= rating_for @staff_member, "smiling" %>
      <br>
      Kindness: <%= rating_for @staff_member, "kindness" %>
      <br>
      Friendly: <%= rating_for @staff_member, "friendly" %>
      <br>
      Professional: <%= rating_for @staff_member, "professional" %>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_staff_member_path(@staff_member) %> |
<%= link_to 'Back', staff_members_path %>

app/views/store/index.html.erb
<div class="row">

<% @products.in_groups_of(3, false).each do |group| %>
  <div class='row'>

    <% group.each do |product| %>
    
    <div class='col-md-4'>

        <div class="thumbnail">

               <div class="caption">

        <h3 ><%= product.title %> </h3>
         <p ><%= product.decription %> </p>
        <%= product.price %>
        <%= product.image %>
       


         <%= form_tag ordered_products_path(product_id: product) do %>
                <div class="text-center"><%= text_field_tag :quantity, params[:quantity]=1,size:"3" %>
                <%= submit_tag 'Add to cart', class: "btn btn-primary" %> </div>
              <% end %>

                </div> <!-- end caption-->
           
    </div><!-- end thumbail-->

  </div> <!-- end col-md-4 -->
      
    <% end %>

</div> <!-- end row -->
<% end %>



</div>